#pragma once
#include <windows.h>
#include <tchar.h>

struct _LMPC_CONFIG;
typedef struct _LMPC_CONFIG LMPC_CONFIG, *HLMPC_CONFIG;

#define LMPC_CFG_ADDRESS 0
#define LMPC_CFG_PORT 1
#define LMPC_CFG_SECRET 2

HRESULT LmpcCfgGetPath(LPTSTR*);

HRESULT LmpcCfgLoad(HLMPC_CONFIG*);
HRESULT LmpcCfgLoadFromPath(LPCTSTR, HLMPC_CONFIG*);

HRESULT LmpcCfgSave(HLMPC_CONFIG);

HRESULT LmpcCfgFieldRead(HLMPC_CONFIG, DWORD);
HRESULT LmpcCfgFieldWrite(HLMPC_CONFIG, DWORD);

HRESULT LmpcCfgFieldGet(HLMPC_CONFIG, DWORD, LPTSTR*);

HRESULT LmpcCfgFieldToWindow(HLMPC_CONFIG, DWORD, HWND);
HRESULT LmpcCfgFieldFromWindow(HLMPC_CONFIG, DWORD, HWND);

HRESULT LmpcCfgDestroy(HLMPC_CONFIG);
