#pragma once
#include <windows.h>
#include "config.h"

struct _LMPC_SERVER;
typedef struct _LMPC_SERVER LMPC_SERVER, *HLMPC_SERVER;

typedef struct _LMPC_PACKET
{
	DWORD Signature;
	UINT Time;
	BYTE Hash[32];
} LMPC_PACKET, *PLMPC_PACKET;

typedef const LMPC_PACKET* PCLMPC_PACKET;

HRESULT LmpcSrvCreate(HLMPC_CONFIG, HLMPC_SERVER*);
HRESULT LmpcSrvDestroy(HLMPC_SERVER);

HRESULT LmpcSrvSetCallback(HLMPC_SERVER, HWND, UINT);

HRESULT LmpcSrvStart(HLMPC_SERVER);
HRESULT LmpcSrvStop(HLMPC_SERVER);

LRESULT LmpcSrvHandleSelect(HLMPC_SERVER, WPARAM, LPARAM);
HRESULT LmpcSrvHandlePacket(HLMPC_SERVER, PCLMPC_PACKET, SIZE_T);
HRESULT LmpcSrvCheckPacket(HLMPC_SERVER, PCLMPC_PACKET, SIZE_T);
